[tool.poetry]
name = "backend-internship-app"
version = "0.1.0"
description = ""
authors = ["Ahmed Elsayed <<ahm.abdelwahab@nu.edu.eg>>"]
readme = "README.md"
packages = [{include = "backend_internship_app"}]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.1.2"
djangorestframework = "^3.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
